import MainSidebar from "@/components/main-side-bar";
import Navbar from "@/components/navbar";
import db from "@/lib/db";
import { auth } from "@clerk/nextjs";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Talk To PDF",
    // description: "Generated by create next app",
};

export default async function ChatIdLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { userId } = auth();
    let chats = await db.chat.findMany({
        where: {
            userId: userId as string,
        },
    });
    chats = chats.reverse();

    if (!userId) {
        redirect("/");
    }

    return (
        <div className="relative h-full">
            <div className="hidden h-full md:flex md:w-80 md:flex-col md:fixed md:inset-y-0 border-r">
                <MainSidebar chats={chats} />
            </div>
            <main className="md:pl-80">
                <Navbar />

                <div
                    className={
                        "text-default pb-1 h-[calc(100dvh_-_48px)] flex flex-col items-center"
                    }
                >
                    {children}
                </div>
            </main>
        </div>
    );
}
